# For more info on HTTP files go to https://aka.ms/vs/httpfile
GET https://localhost:7169/product

### Get all values
GET https://localhost:7169/api/values

### Create a new item
POST https://localhost:7169/product
Content-Type: application/json

{
  "name": "Orange21",
  "description": "big",
  "price": "1515",
  "minprice":"33",
  "storeid":"35ae9dcb-7ba0-4929-baea-d339b5e4523a"
}


